const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const ESLintPlugin = require('eslint-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const StylelintPlugin = require('stylelint-webpack-plugin');
const globals = require('./globals');

const isDevelopment = process.env.NODE_ENV !== 'production';
console.log(`isDevelopment: ${isDevelopment}`, globals);

module.exports = {
	entry: {
		app: './src/index.tsx',
	},
	output: {
		filename: '[name].bundle.[contenthash].js',
		chunkFilename: '[name].chunk.bundle.[contenthash].js',
		path: path.resolve(__dirname, 'dist'),
		publicPath: '/',
	},
	stats: 'errors-warnings',
	resolve: {
		extensions: ['.mjs', '.js', '.jsx', '.json', '.ts', '.tsx'],
		alias: {
			'@actions': path.resolve(__dirname, 'src/actions'),
			'@api': path.resolve(__dirname, 'src/api'),
			'@assets': path.resolve(__dirname, 'src/assets'),
			'@components': path.resolve(__dirname, 'src/components'),
			'@config': path.resolve(__dirname, 'src/config'),
			'@constants': path.resolve(__dirname, 'src/constants'),
			'@containers': path.resolve(__dirname, 'src/containers'),
			'@context': path.resolve(__dirname, 'src/context'),
			'@features': path.resolve(__dirname, 'src/features'),
			'@hooks': path.resolve(__dirname, 'src/hooks'),
			'@src': path.resolve(__dirname, 'src'),
			'@utils': path.resolve(__dirname, 'src/utils'),
			'@views': path.resolve(__dirname, 'src/views'),
			'@db': path.resolve(__dirname, 'src/store'),
			'@utils': path.resolve(__dirname, 'src/utils'),
		},
	},
	module: {
		rules: [
			{
				// Include ts, tsx, js, and jsx files.
				test: /\.tsx?$/,
				exclude: [
					/node_modules/,
					path.resolve(__dirname, 'static'),
					/sw\.js$/,
					/service-worker\.js$/,
				],
				use: {
					loader: 'babel-loader',
					options: {
						cacheDirectory: true,
					},
				},
			},
			{
				test: /\.(s*)css$/,
				include: /node_modules/,
				use: [
					isDevelopment
						? {
								loader: 'style-loader',
								options: {
									esModule: false,
								},
						  }
						: {
								loader: MiniCssExtractPlugin.loader,
								options: {
									esModule: false,
								},
						  },
					'css-loader',
				],
			},
			{
				test: /\.(s*)css$/,
				exclude: /node_modules/,
				use: [
					{
						loader: MiniCssExtractPlugin.loader,
						options: {
							esModule: false,
							// only enable hot in development
							// hmr: process.env.NODE_ENV === "local",
							// if hmr does not work, this is a forceful method.
							// reloadAll: true
						},
					},
					{
						loader: '@teamsupercell/typings-for-css-modules-loader',
						options: {
							banner: '// autogenerated by typings-for-css-modules-loader. \n// Please do not change this file!',
							formatter: 'prettier',
						},
					},
					// Translates CSS into CommonJS
					{
						loader: 'css-loader',
						options: {
							importLoaders: 1,
							// modules: false,
						},
					},
					{
						loader: 'postcss-loader',
						options: {
							postcssOptions: {},
							sourceMap: true,
						},
					},
					{
						loader: 'sass-loader',
						options: {
							sourceMap: true,
							// Prefer `dart-sassRules`
							implementation: require('sass'),
						},
					},
					/* {
						loader: 'sass-resources-loader',
						options: {
							// Provide array of paths to the file with resources
							resources: [
								path.resolve(
									__dirname,
									'src/assets/styles/variables.scss',
								),
							],
						},
					}, */
				],
			},
			{
				test: /\.(png|jpe?g|gif|svg)$/i,
				use: [
					{
						loader: 'file-loader',
						options: {
							name: '[name]-[hash].[ext]',
							outputPath: 'img/', // file pack output path, is relative path for `dist`
							publicPath: '/img/', // css file will use, is absolute path for server
						},
					},
				],
			},
		],
	},
	plugins: [
		new NodePolyfillPlugin(),
		new ForkTsCheckerWebpackPlugin({
			eslint: {
				files: './src/**/*.{ts,tsx,js,jsx}', // required - same as command `eslint ./src/**/*.{ts,tsx,js,jsx} --ext .ts,.tsx,.js,.jsx`
			},
			typescript: {
				diagnosticOptions: {
					semantic: true,
					syntactic: true,
				},
				mode: 'write-references',
			},
		}),
		new StylelintPlugin({
			config: {
				extensions: ['css', 'scss', 'sass'],
				rules: {
					'color-no-invalid-hex': true,
				},
			},
		}),
		// new webpack.IgnorePlugin({
		// 	resourceRegExp: /^\.\/locale$/,
		// 	contextRegExp: /moment/,
		// }),
		new HtmlWebpackPlugin({
			title: 'Production',
			template: './src/index.html',
			hash: true,
			showErrors: false,
			environment: JSON.stringify(process.env.NODE_ENV),
		}),
		/* new WorkerPlugin(), */
		new MiniCssExtractPlugin({
			// Options similar to the same options in webpackOptions.output
			// both options are optional
			filename:
				process.env.NODE_ENV === 'local' ? '[name].css' : '[name].css',
			chunkFilename:
				process.env.NODE_ENV === 'local' ? '[name].css' : '[name].css',
		}),
		new webpack.DefinePlugin(globals),
		new CopyPlugin({
			patterns: [
				{
					from: 'public',
					to: 'public',
					noErrorOnMissing: true,
				},
			],
		}),
		new ESLintPlugin({
			extensions: ['ts', 'tsx'],
			exclude: ['node_modules'],
		}),
	],
};
